### ISSUE TITLE
Incorrect display of base face in certain CPs

### ISSUE THREAD

**Issue by OrigamiDraw** [origamimagiro/flat-folder#17]
Some very simple CPs don't appear correctly in their folded form. It looks like one of the faces (likely the one serving as the base) doesn't Flip and appears on top of other faces.
Here are very simple examples (.cp files) with a single fold:
3 -200.0 -100.0 200.0 200.0
1 -200.0 -200.0 200.0 -200.0
1 200.0 -200.0 200.0 200.0
1 -200.0 200.0 200.0 200.0
1 -200.0 200.0 -200.0 -100.0
1 -200.0 -200.0 -200.0 -100.0
and with three folds:
3 -100.0 -200.0 200.0 200.0
1 -200.0 -200.0 -100.0 -200.0
1 200.0 -200.0 -100.0 -200.0
1 200.0 -200.0 200.0 200.0
1 -200.0 200.0 -200.0 -100.0
1 -200.0 -200.0 -200.0 -100.0
1 -200.0 200.0 0.0 200.0
3 0.0 200.0 -200.0 -100.0
2 -200.0 -100.0 200.0 200.0
1 0.0 200.0 200.0 200.0

**Comment by origamimagiro** [comment]
Nice catch again! You are an excellent bug catcher! 

Looks like there is problem with the `M.interior_point` function. Both files you gave construct a very non-convex cell polygon whose calculated interior point is not interior (turning on text will make that apparent). Current implementation checks for triangles that do not contain other vertices of the polygon, but it does not check crossing edges, which it should (that's the bug). That code definitely needs fixing.

Luckily the only two places that code is used for is (1) locating text labels for cells (which is separate from solving code) and (2) computing the face_cell and cell_face adjacency maps (which will be removed when issue #10 is handled).

**Comment by OrigamiDraw** [comment]
You are FAST! I had no clue where to even start investigating the issue. Your analysis makes sense and matches the symptoms, including what happens in the overlap graph. So, I suppose it can happen with any number of faces at the same time, not just a single "base face" as I had assumed.

**Comment by origamimagiro** [comment]
Turns out that the algorithm I was using for `M.interior_point` was actually correct (returns centroid of largest ear of the polygon), but when checking whether another point `p` is contained in each potential ear, I was checking the point against the entire polygon instead of just the ear (`M.convex_contains_point(P, p)` should have been  `M.convex_contains_point([p1, p2, p3], p)`). However, I've decided to forgo the call to `M.convex_contains_points` entirely since a triangle has a constant number of points, and `M.convex_contains_points` can be removed when issue #10 is closed.
