### ISSUE TITLE
Numerical instability in M.intersect

### ISSUE THREAD

**Issue by OrigamiDraw** [origamimagiro/flat-folder#23]
At the moment, M.intersect calculates the cross product of the vectors representing the two segments. It then compares this to zero to check whether the segments are parallel. However, due to rounding errors, this value can sometimes be non-zero even in the case of parallel segments. This bypasses the check and causes the function to return an incorrect intersection point. Further down the line, this causes some CPs to not fold properly.

**Comment by origamimagiro** [comment]
I'm hoping commit [9ae996f](https://github.com/origamimagiro/flat-folder/commit/9ae996f974bfd706d7cd7f2fcd0ad66cbec66315) fixes this issue. Please let me know here if you continue to have problems with the intersect code.

**Comment by OrigamiDraw** [comment]
Unfortunately no, it didn't fix the issue we have seen. I am afraid things get pretty unpredictable when we are at the limit of precision.
Here is what we have:
a: [0.4705882352941144, 0.3235294117647049]
b: [0.47058823529411425, 0.308823529411765]
c: [0.4705882352941126, 0.20588235294117588]
d: [0.47058823529411375, 0.2794117647058818]
eps: 0.00004901960784309193
denom: -1.0408340855860843e-17
s_num: -6.938893903907228e-18
t_num: -9.540979117872439e-18
s: 0.6666666666666666
t: 0.9166666666666666
p: [0.4705882352941143, 0.3137254901960783]

**Comment by origamimagiro** [comment]
OK, I give. Added an actual threshold at $10^{-16}$. This should fix your example, and it fixes the same issue for a large box-pleated model that I had that also wouldn't fold. Hopefully it fixes yours too!

**Comment by robbykraft** [comment]
i was watching this thread play out. glad to see this get adopted. imo, it's totally necessary.

small suggestion, you can remove the last two additional if statements, and incorporate the check into the already existing line:

```javascript
if ((s < 0) || (1 < s) || (t < 0) || (1 < t)) { return; }
```

becomes:

```javascript
if ((s < M.FLOAT_EPS) || (1 - M.FLOAT_EPS < s) || (t < M.FLOAT_EPS) || (1 - M.FLOAT_EPS < t)) { return; }
```

but that's a superficial change.

another question i think is more substantive: why not use the calculated epsilon instead of an absolute epsilon here? the difference relating to how messy of an input file are you hoping to accept. I often use this as an example: [KNL Dragon](https://langorigami.com/wp-content/uploads/2015/08/knl_dragon_cp.pdf), which is actually pretty messy when you open in Illustrator and zoom in.

i know you're using calculated epsilon for planar-graph building. honestly, i'm not sure exactly how the parallel epsilon plays out in messy file import. would be nice to set up some testing to more clearly establish the limits of what level of messy is acceptable, wherever you prefer that line to be. and then see how much the parallel line epsilon matters.

**Comment by origamimagiro** [comment]
Unfortunately, I don't think the change you suggest would actually be a superficial change? Though I might be misinterpreting what you mean by "last two additional `if` statements.

Currently we bound `s_num`, `t_num`, and `denom` by `M.FLOAT_EPS` when they are near zero, before calculating `s` and `t`. If we instead bound `s` and `t`, when we compute them, division of a thing near zero by another thing near zero could result in something between and far from zero and one. In particular, waiting to bound `s` and `t` after will be problematic for exactly the situation in the example discussed in this issue. We definitely want two different epsilons here, since errors in floating-point division are a property of the machine precision, not the crease pattern precision.

I don't think this floating-point check will affect messy files so much. If two segments are close to parallel and intersect, we would identify the case in the first `if` statement of `M.intersect` before getting to this added check. I believe the current fix only removes false positives of intersections that are the result of dividing things near zero by things near zero. 

Usually the bigger problem you point out is messy crease patterns failing the computed epsilon check (second bullet of point 2 of README How To). That's the description of how this file importer will import a messy file. If a crease pattern fails that, it's pretty messy from a computation standpoint, and I don't think I want this software to make assumptions on how to clean up them up.

**Comment by robbykraft** [comment]
right, that was a sloppy assumption on my part. my bad. my suggestion (about the last two additional if statements) assumes you wanted to use the larger epsilon. however, if you could humor me for a second, i believe i do have a cohesive suggestion.

this suggestion is that there is an alternative approach which replaces all occurrences of `FLOAT_EPS` with the larger epsilon. in your segment intersection algorithm, two things are being tested with `if` statements:

1. parallel lines
2. intersection near to an endpoint

regarding 2, the reason i suggested using the "normalized" (between 0 and 1) `s` and `t` values when comparing segment intersection to its endpoints is because you are already doing something similar in your point-merging planar graph method- establishing an invalid radius around each point. that radius being the larger epsilon. (of course in the segment intersection this epsilon radius is scaled to the length of the segment, each segment having a different length, but i think that's fine they'll be similar enough)

and regarding,

> division of a thing near zero by another thing near zero

if you use the larger epsilon when you do the parallel test too, this will never happen. it gets rid of all cases of a "thing near zero", dividing a small number by another small number still works, everything is just on a smaller scale.

/explanation

first of all, i think what i explained is consistent. did i make a mistake in there?

but again it really comes down to a preference thing. honestly, i hope you consider but shelve my suggestion for now. your approach is much simpler. and i think will result in fewer bugs too. if you end up doing testing, i would build a couple edge cases around this stuff just to double check. and then reconsider this if necessary. ultimately however, i did want to point out the segment-endpoint-radius and planarize-merge-radius thing which felt a little inconsistent.

**Comment by origamimagiro** [comment]
I think I may not be understanding your suggestion? 

The current algorithm computes a crease pattern `eps` that scales with the shortest length of any edge of the input. This same `eps` is used for all cleanup related code, i.e., evaluating whether vertices are the same or coincident to lines. Crucially this is not a different normalized `eps` for each segment because I want to ensure the same precision across the crease pattern, not varying locally across the crease pattern.

As I said previously, I definitely want both levels of epsilon. Bounding the size of the denominator or numerator by the distance epsilon is problematic because the denominator/numerators are each computed as the product of coordinates. The errors multiply, so we need to maintain about double the precision as when dealing with just distances. Thresholding these values to the crease pattern `eps` would be like thresholding the area of polygon by a length. The units don't match, and the check would be a lot looser than the rest of the code. Yes, the dividing zero by zero thing definitely would be caught by using a larger epsilon, but it would also be much more permissive dismissing two lines as parallel when they might actually properly intersect. 

A possible alternative would be to bound the denominator/numerators by something proportional to `eps*eps`. However, because the precision of the floating-point division is dependent on Javascript's precision, not the precision of the input crease pattern, I think using a different epsilon (independent of the crease pattern) is appropriate. I picked $10^16$ because the precision of a floating-point double (i.e., Javascript Number) is $53$ bits, or about $\log_{10}(2^{53}) \approx 16$ decimal digits of precision. Should this bound be looser, like maybe $10^{15}$ or $10^{14}$ instead? Perhaps. But $10^{16}$ seems to be working ok right now.
