### ISSUE TITLE
Empty overlap graph cells

### ISSUE THREAD

**Issue by origamimagiro** [origamimagiro/flat-folder#26]
It is possible for cells of the overlap graph to overlap no faces, i.e., when the folding forms a loop around empty space. Here is a simple example of such a folding.

![cycle_img](https://user-images.githubusercontent.com/5639582/182748721-2a62dc1b-91d3-4d84-8ef3-0ace784cf09d.svg)

The existing code throws a `RangeError` in `EF_SE_SC_CD_2_SD`, but I haven't gotten a chance to investigate the problem. My guess is it should be a simple fix, but the code was not written with empty interior cells in mind.

**Comment by OrigamiDraw** [comment]
Commit 1413e3b may have fixed the problem in the initial overlap graph (the X-ray view) but after folding, empty cells are still colored and selectable. The folded view appears correctly.

**Comment by origamimagiro** [comment]
I'm not sure I understand? It currently behaves as intended: draws cells and indicates their overlap with faces. One can still interact with an empty cell, and it still correctly indicates overlap (i.e. colors none of the faces of the CP yellow).

**Comment by OrigamiDraw** [comment]
Well, it may be intentional, I don't know. This is before folding:
<img width="1303" alt="Screen Shot 2022-08-12 at 12 20 58 PM" src="https://user-images.githubusercontent.com/110136377/184336222-f1393996-4257-4dfe-a44a-d2682d007933.png">
and this is after:
<img width="1303" alt="Screen Shot 2022-08-12 at 12 20 27 PM" src="https://user-images.githubusercontent.com/110136377/184336288-c892e265-29eb-4a7b-a473-f1c86af45466.png">
The center square is now opaque and can be selected:
<img width="1303" alt="Screen Shot 2022-08-12 at 12 20 32 PM" src="https://user-images.githubusercontent.com/110136377/184336364-bed1b9b0-117d-433a-8cef-9530e268fe18.png">
In the CP, there is of course no corresponding face but edges are shown. This may actually be helpful.

However, on a more complex CP giving more nuances of grey in the overlap graph, the white empty cell is a bit confusing:
<img width="805" alt="Screen Shot 2022-08-12 at 12 25 09 PM" src="https://user-images.githubusercontent.com/110136377/184337205-6a1de6c0-5396-4652-85a1-57ab072009a0.png">

**Comment by OrigamiDraw** [comment]
From the coding standpoint, I also wonder how this comes to be. If empty cells are no longer included in EF_SE_SC_CD_2_SD, how do they come back in the overlap graph?

**Comment by origamimagiro** [comment]
Empty cells are still included in `SD` (and more importantly in `CD`); the renderer for the folded state just doesn't draw them. The overlap graph in currently computed as the arrangement of lines in the folded model. Since it constructs the overlap graph from line information and not face information, it does not know whether a cell is empty or not when building the graph. Of course, when we build the cell-face adjacencies, we could identify empty cells and remove them, but I think I'm ok with the current behavior.

**Comment by OrigamiDraw** [comment]
I see; I hadn't actually looked at 1413e3b in detail. Yet I am still disturbed by this white space between the kangaroo's legs. How about we just render it transparent? The necessary information can easily be retrieved from CF, like this:

    CF_2_Cbw: (CF) => {
        return GUI.CF_2_Clayer(CF).map(l => (l == 0) ?
            `hsla(0, 0%, 100%, 0.0)` :
            `hsl(0, 0%, ${Math.ceil((1 - l*0.8)*100)}%)`);
    },

which would give a more natural-looking graph (also in the exported svg):
<img width="806" alt="Screen Shot 2022-08-13 at 11 28 40 PM" src="https://user-images.githubusercontent.com/110136377/184511313-467f0bce-45c9-415a-af30-f5445c0b180f.png">

and the empty cell would still be selectable:
<img width="806" alt="Screen Shot 2022-08-13 at 11 27 49 PM" src="https://user-images.githubusercontent.com/110136377/184511316-00d962fd-b9bc-404e-9b40-106c2bb5e491.png">

**Comment by origamimagiro** [comment]
Good point. Yup, that's an easy place to change the rendering. Thanks! Pushed the change.
